In [129]:
# 1. 데이터 불러오기
import pandas as pd
url='https://raw.githubusercontent.com/sehakflower/data/main/titanic.csv'
titanic_df= pd.read_csv(url,sep='\t')
titanic_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  156 non-null    int64
 1   Survived     156 non-null    int64
 2   Pclass       156 non-null    int64
 3   Name         156 non-null    str
 4   Sex          156 non-null    str
 5   Age          126 non-null    float64
 6   SibSp        156 non-null    int64
 7   Parch        156 non-null    int64
 8   Ticket       156 non-null    str
 9   Fare         156 non-null    float64
 10  Cabin        31 non-null     str
 11  Embarked     155 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 14.8 KB

In [130]:
# 컬럼명 변경
new_columns=['passengerId', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket', 'fare', 'cabin', 'embarked']
titanic_df.columns=new_columns
titanic_df.columns

Index(['passengerId', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp',
       'parch', 'ticket', 'fare', 'cabin', 'embarked'],
      dtype='str')

In [131]:
# isna 함수
titanic_df['age'][titanic_df['age'].isna()]

5     NaN
17    NaN
19    NaN
26    NaN
28    NaN
29    NaN
31    NaN
32    NaN
36    NaN
42    NaN
45    NaN
46    NaN
47    NaN
48    NaN
55    NaN
64    NaN
65    NaN
76    NaN
77    NaN
82    NaN
87    NaN
95    NaN
101   NaN
107   NaN
109   NaN
121   NaN
126   NaN
128   NaN
140   NaN
154   NaN
Name: age, dtype: float64

In [132]:
# isnull 함수
titanic_df['age'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
151    False
152    False
153    False
154     True
155    False
Name: age, Length: 156, dtype: bool

In [133]:
# inull 함수로 결측치인 NaN 값 추출
titanic_df['age'][titanic_df['age'].isnull()]

5     NaN
17    NaN
19    NaN
26    NaN
28    NaN
29    NaN
31    NaN
32    NaN
36    NaN
42    NaN
45    NaN
46    NaN
47    NaN
48    NaN
55    NaN
64    NaN
65    NaN
76    NaN
77    NaN
82    NaN
87    NaN
95    NaN
101   NaN
107   NaN
109   NaN
121   NaN
126   NaN
128   NaN
140   NaN
154   NaN
Name: age, dtype: float64

In [134]:
# NaN 값 개수 확인
titanic_df['age'][titanic_df['age'].isnull()].isnull().sum()

np.int64(30)

In [135]:
# notnull 함수
titanic_df['age'].notnull()

0       True
1       True
2       True
3       True
4       True
       ...
151     True
152     True
153     True
154    False
155     True
Name: age, Length: 156, dtype: bool

In [136]:
# notnull로 NaN이 아닌값만 추출
titanic_df['age'][titanic_df['age'].notnull()]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
150    51.0
151    22.0
152    55.5
153    40.5
155    51.0
Name: age, Length: 126, dtype: float64

In [137]:
# notnull 활용해 age 열에서 NaN이 아닌 데이터를 검색, age와 name 출력
titanic_df.loc[titanic_df['age'].notnull(),['age', 'name']]

      age                                               name
0    22.0                            Braund, Mr. Owen Harris
1    38.0  Cumings, Mrs. John Bradley (Florence Briggs Th...
2    26.0                             Heikkinen, Miss. Laina
3    35.0       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4    35.0                           Allen, Mr. William Henry
..    ...                                                ...
150  51.0                         Bateman, Rev. Robert James
151  22.0                  Pears, Mrs. Thomas (Edith Wearne)
152  55.5                                   Meo, Mr. Alfonzo
153  40.5                    van Billiard, Mr. Austin Blyler
155  51.0                        Williams, Mr. Charles Duane

[126 rows x 2 columns]

In [138]:
# notnull 활용해 결측치가 있는 행을 추출하고 age열에서 결측치인 행과 해당하는 name 열의 값을 추출
titanic_df.loc[titanic_df['age'].isnull(),['age', 'name']]

     age                                            name
5    NaN                                Moran, Mr. James
17   NaN                    Williams, Mr. Charles Eugene
19   NaN                         Masselmani, Mrs. Fatima
26   NaN                         Emir, Mr. Farred Chehab
28   NaN                   O'Dwyer, Miss. Ellen "Nellie"
29   NaN                             Todoroff, Mr. Lalio
31   NaN  Spencer, Mrs. William Augustus (Marie Eugenie)
32   NaN                        Glynn, Miss. Mary Agatha
36   NaN                                Mamee, Mr. Hanna
42   NaN                             Kraeff, Mr. Theodor
45   NaN                        Rogers, Mr. William John
46   NaN                               Lennon, Mr. Denis
47   NaN                       O'Driscoll, Miss. Bridget
48   NaN                             Samaan, Mr. Youssef
55   NaN                               Woolner, Mr. Hugh
64   NaN                           Stewart, Mr. Albert A
65   NaN                        Moubarek, Master. Gerios
76   NaN                               Staneff, Mr. Ivan
77   NaN                        Moutal, Mr. Rahamin Haim
82   NaN                  McDermott, Miss. Brigdet Delia
87   NaN                   Slocovski, Mr. Selman Francis
95   NaN                     Shorney, Mr. Charles Joseph
101  NaN                Petroff, Mr. Pastcho ("Pentcho")
107  NaN                          Moss, Mr. Albert Johan
109  NaN                             Moran, Miss. Bertha
121  NaN                      Moore, Mr. Leonard Charles
126  NaN                             McMahon, Mr. Martin
128  NaN                               Peter, Miss. Anna
140  NaN                   Boulos, Mrs. Joseph (Sultana)
154  NaN                           Olsen, Mr. Ole Martin

In [139]:
# 결측치 처리 
titanic_df.head()

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [140]:
# cabin 열의 결측치를 'N'으로 변경
titanic_df['cabin']=titanic_df['cabin'].fillna('N')
titanic_df['cabin']

0         N
1       C85
2         N
3      C123
4         N
       ...
151      C2
152       N
153       N
154       N
155       N
Name: cabin, Length: 156, dtype: str

In [141]:
# cabin 열 값의 개수 확인
titanic_df['cabin'].value_counts()

cabin
N              125
C123             2
C23 C25 C27      2
D26              2
C85              1
E46              1
G6               1
C103             1
D56              1
A6               1
B78              1
D33              1
B30              1
C52              1
B28              1
C83              1
F33              1
F G73            1
E31              1
A5               1
D10 D12          1
C110             1
B58 B60          1
E101             1
F E69            1
D47              1
B86              1
F2               1
C2               1
Name: count, dtype: int64

In [142]:
# 첫 번째 인덱스 값 확인
titanic_df['cabin'][0]

'N'

In [143]:
# apply와 lambda 식을 이용해 데이터의 첫 문자만 남기기 
titanic_df['cabin']=titanic_df['cabin'].apply(lambda x : x[0])
titanic_df['cabin']

0      N
1      C
2      N
3      C
4      N
      ..
151    C
152    N
153    N
154    N
155    N
Name: cabin, Length: 156, dtype: str

In [144]:
titanic_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   passengerId  156 non-null    int64
 1   survived     156 non-null    int64
 2   pclass       156 non-null    int64
 3   name         156 non-null    str
 4   sex          156 non-null    str
 5   age          126 non-null    float64
 6   sibsp        156 non-null    int64
 7   parch        156 non-null    int64
 8   ticket       156 non-null    str
 9   fare         156 non-null    float64
 10  cabin        156 non-null    str
 11  embarked     155 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 14.8 KB

In [145]:
# 데이터프레임(titanic_df) 복제
titanic_df_copy=titanic_df.copy()
titanic_df_copy

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,N,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,N,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,N,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,N,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,N,C

In [146]:
# 결측치를 찾는(True로 표시) isnull 함수를 이용
titanic_df_copy['age'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
151    False
152    False
153    False
154     True
155    False
Name: age, Length: 156, dtype: bool

In [147]:
# mean 함수로 열의 평균값 구하고 fillna 함수로 결측치 채우기
titanic_df_copy['age']=titanic_df_copy['age'].fillna(titanic_df_copy['age'].mean())
titanic_df_copy['age']

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
151    22.000000
152    55.500000
153    40.500000
154    28.141508
155    51.000000
Name: age, Length: 156, dtype: float64

In [148]:
# copy(원본 데이터프레임을 유지한 채 새로운 주소로 복사)
copy_titanic_df=titanic_df.copy()
copy_titanic_df

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,N,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,N,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,N,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,N,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,N,C

In [149]:
# hex 함수로 원본과 복사된 데이터 프레임의 주소를 확인
hex(id(titanic_df))

'0x1f833a16740'

In [150]:
# 위 코드와 동일함
hex(id(copy_titanic_df))

'0x1f833a15860'

In [151]:
# copy 한 데이터프레임이 서로 같은지 확인
titanic_df.head()

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,N,S

In [152]:
# copy 한 데이터프레임이 서로 같은지 확인
copy_titanic_df.head()

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,N,S

In [153]:
copy_titanic_df['age']=0
copy_titanic_df.head()

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,0,0,0,373450,8.0500,N,S

In [154]:
# age값 변경 후 copy한 데이터프레임
titanic_df.head()

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,N,S

In [155]:
# 데이터 통계치 확인
titanic_df.describe()

,passengerId,survived,pclass,age,sibsp,parch,fare
count,156.000000,156.000000,156.000000,126.000000,156.000000,156.000000,156.000000
mean,78.500000,0.346154,2.423077,28.141508,0.615385,0.397436,28.109587
std,45.177428,0.477275,0.795459,14.613880,1.056235,0.870146,39.401047
min,1.000000,0.000000,1.000000,0.830000,0.000000,0.000000,6.750000
25%,39.750000,0.000000,2.000000,19.000000,0.000000,0.000000,8.003150
50%,78.500000,0.000000,3.000000,26.000000,0.000000,0.000000,14.454200
75%,117.250000,1.000000,3.000000,35.000000,1.000000,0.000000,30.371850
max,156.000000,1.000000,3.000000,71.000000,5.000000,5.000000,263.000000

In [156]:
# sum 함수
titanic_df.sum()

passengerId                                                12246
survived                                                      54
pclass                                                       378
name           Braund, Mr. Owen HarrisCumings, Mrs. John Brad...
sex            malefemalefemalefemalemalemalemalemalefemalefe...
age                                                      3545.83
sibsp                                                         96
parch                                                         62
ticket         A/5 21171PC 17599STON/O2. 31012821138033734503...
fare                                                   4385.0956
cabin          NCNCNNENNNGCNNNNNNNNNDNANNNCNNNBNNNNNNNNNNNNNN...
embarked       SCSSSQSSSCSSSSSSQSSCSSQSSSCSQSCCQSCSCSSCSSCCQS...
dtype: object

In [157]:
# count 함수
titanic_df.count()

passengerId    156
survived       156
pclass         156
name           156
sex            156
age            126
sibsp          156
parch          156
ticket         156
fare           156
cabin          156
embarked       155
dtype: int64

In [158]:
# max 함수
titanic_df.max()

passengerId                                156
survived                                     1
pclass                                       3
name           van Billiard, Mr. Austin Blyler
sex                                       male
age                                       71.0
sibsp                                        5
parch                                        5
ticket                             W.E.P. 5734
fare                                     263.0
cabin                                        N
embarked                                     S
dtype: object

In [159]:
# min 함수
titanic_df.min()

passengerId                                                 1
survived                                                    0
pclass                                                      1
name           Ahlin, Mrs. Johan (Johanna Persdotter Larsson)
sex                                                    female
age                                                      0.83
sibsp                                                       0
parch                                                       0
ticket                                                 110465
fare                                                     6.75
cabin                                                       A
embarked                                                    C
dtype: object

In [ ]:
# mean 함수
titanic_df.mean()

passengerId    78.500000
survived        0.346154
pclass          2.423077
age            28.141508
sibsp           0.615385
parch           0.397436
fare           28.109587
dtype: float64

In [161]:
# median 함수
titanic_df.median()

TypeError: Cannot perform reduction 'median' with string dtype

In [ ]:
# mode 함수
titanic_df.mode()

In [ ]:
# mad 함수
titanic_df.mad()

In [ ]:
# var 함수
titanic_df.var()

In [ ]:
# std 함수(표준편차 구하는 함수)
titanic_df.std()

In [ ]:
# skew 함수(왜도 구하는 함수)
titanic_df.skew()

In [ ]:
# kurt 함수(첨도 구하는 함수)
titanic_df.kurt()

In [ ]:
#특정 열 통계치 구하기
titanic_df['age'].max() # 최대값 구하기
titanic_df['age'].min() # 최솟값 구하기
titanic_df['age'].sum() # 합계 구하기
titanic_df['age'].count() # 개수 구하기
titanic_df['age'].mean() # 평균값 구하기
titanic_df['age'].sum()/titanic_df['age'].count() # 평균값 구하기
titanic_df['age'].std() # 표준편차 구하기
titanic_df['age'].median() # 중간값 구하기
titanic_df['age'].mode() # 최빈값 구하기