## 1. 파이썬 파일 처리

In [806]:
sample_file = 'data/sample.txt'

In [807]:
# 파일을 open하여 전체 내용을 읽어서 출력

with open(sample_file, mode='rt') as f:
    content = f.read()
    print(content)

print("----- 끝 -----")

나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.

----- 끝 -----

In [808]:
# 파일을 open하고 한 줄씩 읽어서 출력하기
with open(sample_file, 'r') as f:
    lines = f.readlines()
    print(lines)
    for line in lines:
        print(line, end="")

print("----- 끝 -----")

['나의 속도로\n', '\n', '조금 늦어도 괜찮다.\n', '남들과 같은 길을 갈 필요도 없다.\n', '\n', '오늘 배운 것 하나,\n', '오늘 해결한 문제 하나가\n', '조금씩 나의 실력이 된다.\n', '\n', '결과가 보이지 않는 날에도\n', '나는 앞으로 가고 있다.\n', '\n', '빠르게 가는 것보다\n', '멈추지 않는 것이 중요하다.\n', '\n', '오늘의 작은 한 걸음이\n', '내일의 나를 만든다.\n', '\n', '나는 늦은 것이 아니라\n', '나의 속도로 가고 있다.\n']
나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.
----- 끝 -----

In [809]:
# 파일객체에서 한 줄씩 읽어 오기
# 파일 객체 f를 반복문에서 사용하면 파일을 한 줄씩 읽으며,
# 각 줄 끝의 \n도 포함해서 가져옵
with open(sample_file, 'r') as f:
    for line in f:
        print(line, end="")

print("----- 끝 -----")

나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.
----- 끝 -----

In [810]:
# 여러 개의 파일 읽기 (모든 txt 파일을 읽어서 출력하기)
import glob

txt_file_pattern = "data/*.txt"
files = glob.glob(txt_file_pattern)
print(files)

for file in files:
    print(file)
    with open(file, "r") as f:
        print(f.read())

print("----- 끝 -----")

['data\\hello.txt', 'data\\sample.txt', 'data\\score.txt']
data\hello.txt
안녕하세요
hello
내용을 추가합니다.
저장하는 문서 이름,  'w' 대신 'a'를 사용합니다.

data\sample.txt
나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.

data\score.txt
90
100
85
95
----- 끝 -----

## 2. 파이썬 문자열 다루기

In [811]:
# 양쪽 공백 제거
b1=" 작은 일에 성실한 사람은      큰일에도 성실하고 "
b1.strip()

'작은 일에 성실한 사람은      큰일에도 성실하고'

In [812]:
# 왼쪽 문자, 오른쪽 문자, 양쪽 문자 제거
text="....작은 일에 성실한 사람은, 큰일에도 성실하고...."
text = text.strip('.')
text

'작은 일에 성실한 사람은, 큰일에도 성실하고'

In [813]:
# ,로 문자열 분리
text="....작은 일에 성실한 사람은, 큰일에도 성실하고...."
text.split(",")

['....작은 일에 성실한 사람은', ' 큰일에도 성실하고....']

In [814]:
# .으로 문자열 분리
numbers="1. 2. 3. 4. 5. 6"
numbers.split(".")

['1', ' 2', ' 3', ' 4', ' 5', ' 6']

## 3. 판다스로 데이터 가져오기

In [815]:
# 판다스 설치
!pip install pandas

Requirement already satisfied: pandas in C:\Users\USER\anaconda3\envs\pydata26\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\USER\anaconda3\envs\pydata26\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\USER\anaconda3\envs\pydata26\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\USER\anaconda3\envs\pydata26\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\USER\anaconda3\envs\pydata26\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [816]:
# 연습용 sample_data.csv 로딩하기
sample_file = 'data/sample_data.csv'

import pandas as pd
sample_df = pd.read_csv(sample_file)
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [817]:
sample_df.to_csv('data/sampel_data_copy.csv', index=False)

In [818]:
df2 = pd.read_csv('data/sampel_data_copy.csv')
df2

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [819]:
# 타이타닉 데이터 가져오기
titanic_data = 'https://raw.githubusercontent.com/sehakflower/data/main/titanic.csv'

In [820]:
# 데이터를 읽으면서 탭을 기준으로 분리하여 데이터 프레임으로 만들기
t_df = pd.read_csv(titanic_data, sep="\t")
t_df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

# 4. 판다스 데이터 처리

### 4-1. 데이터 구조 및 구성 확인

In [821]:
# 앞부분 확인
sample_df.head()

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston

In [822]:
# 뒷부분 확인
t_df.tail

<bound method NDFrame.tail of      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
151          152         1       1
152          153         0       3
153          154         0       3
154          155         0       3
155          156         0       1

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
151                  Pears, Mrs. Thomas (Edith Wearne)  female  22.0      1
152                                   Meo, Mr. Alfonzo    male  55.5      0
153                    van Billiard, Mr. Austin Blyler    male  40.5      0
154                              Olsen, Mr. Ole Martin    male   NaN      0
155                        Williams, Mr. Charles Duane    male  51.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
151      0            113776  66.6000    C2        S
152      0        A.5. 11206   8.0500   NaN        S
153      2          A/5. 851  14.5000   NaN        S
154      0         Fa 265302   7.3125   NaN        S
155      1          PC 17597  61.3792   NaN        C

[156 rows x 12 columns]>

In [823]:
# 데이터 개수/형태 확인
t_df.shape

(156, 12)

In [824]:
#데이터의 기본 통계치 보기
sample_df.describe()

             Age
count   5.000000
mean   26.200000
std     4.147288
min    22.000000
25%    24.000000
50%    24.000000
75%    29.000000
max    32.000000

In [825]:
# 데이터 구성 정보 확인하기
t_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  156 non-null    int64
 1   Survived     156 non-null    int64
 2   Pclass       156 non-null    int64
 3   Name         156 non-null    str
 4   Sex          156 non-null    str
 5   Age          126 non-null    float64
 6   SibSp        156 non-null    int64
 7   Parch        156 non-null    int64
 8   Ticket       156 non-null    str
 9   Fare         156 non-null    float64
 10  Cabin        31 non-null     str
 11  Embarked     155 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 14.8 KB

In [826]:
# 타이타닉 데이터 구조 및 구성 확인하기
sample_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      str
 1   Age     5 non-null      float64
 2   Gender  7 non-null      str
 3   City    6 non-null      str
dtypes: float64(1), str(3)
memory usage: 356.0 bytes

### 4-2. 컬럼명과 인덱스 정리

In [827]:
# 데이터프레임 복사하기
sample_backup_df = sample_df.copy()
sample_backup_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [828]:
# 열 이름 변경하기 : 모두 소문자로 변경
# new_cols = []
# for col in sample_df.columns:
#     new_cols.append(col.lower())
# sample_df.columns = new_cols
# sample_df
sample_df.columns = [col.lower() for col in sample_df.columns]
sample_df

      name   age gender         city
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [829]:
sample_df = sample_df.rename(columns=str.lower)
sample_df

      name   age gender         city
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [830]:
sample_df = sample_df.rename(columns=str.capitalize)
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [ ]:
# 컬럼명의 앞글자는 소문자로, 나머지는 대문자로 수정(숙제)
sample_df = sample_df.rename(columns=lambda x: x[0].lower() + x[1:].upper())
sample_df

In [832]:
sample_df = sample_backup_df.copy()
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [833]:
# index 확인
t_df.index

RangeIndex(start=0, stop=156, step=1)

In [834]:
t_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [835]:
# 행 데이터 삭제하기
drop_index = [2, 4, 152, 154]
t_df = t_df.drop(drop_index, axis=0)
t_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
149,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
150,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [836]:
# index를 0부터 순서대로 assign 되도록 reset하기
t_df = t_df.reset_index(drop=True)
t_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
3,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
147,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
148,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
149,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
150,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
151,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [837]:
# 컬럼 PassengeId를 index로 설정하기
t_df = t_df.set_index('PassengerId')
t_df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...
150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [838]:
# index(passengerid)를 컬럼으로 만들고, index를 RangeIndex로 reset하기
t_df = t_df.reset_index()
t_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
3,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
147,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
148,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
149,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
150,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
151,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

### 4-3. 데이터 정렬

In [839]:
# 'age' 기준으로 정렬
t_df = t_df.sort_values(by='Age').head(10)
t_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
76,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
5,8,0,3,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,21.0750,NaN,S
14,17,0,3,"Rice, Master. Eugene",male,2.00,4,1,382652,29.1250,NaN,Q
117,120,0,3,"Andersson, Miss. Ellis Anna Maria",female,2.00,4,2,347082,31.2750,NaN,S
41,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C
61,64,0,3,"Skoog, Master. Harald",male,4.00,3,2,347088,27.9000,NaN,S
8,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S
56,59,1,2,"West, Miss. Constance Mirium",female,5.00,1,2,C.A. 34651,27.7500,NaN,S
48,51,0,3,"Panula, Master. Juha Niilo",male,7.00,4,1,3101295,39.6875,NaN,S
22,25,0,3,"Palsson, Miss. Torborg Danira",female,8.00,3,1,349909,21.0750,NaN,S

In [840]:
print(t_df.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [841]:
# 'age' 기준으로 내림차순으로 정렬
t_df = t_df.sort_values(by='Age', ascending=False).head(10)
t_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
22,25,0,3,"Palsson, Miss. Torborg Danira",female,8.00,3,1,349909,21.0750,NaN,S
48,51,0,3,"Panula, Master. Juha Niilo",male,7.00,4,1,3101295,39.6875,NaN,S
56,59,1,2,"West, Miss. Constance Mirium",female,5.00,1,2,C.A. 34651,27.7500,NaN,S
61,64,0,3,"Skoog, Master. Harald",male,4.00,3,2,347088,27.9000,NaN,S
8,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S
41,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C
14,17,0,3,"Rice, Master. Eugene",male,2.00,4,1,382652,29.1250,NaN,Q
5,8,0,3,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,21.0750,NaN,S
117,120,0,3,"Andersson, Miss. Ellis Anna Maria",female,2.00,4,2,347082,31.2750,NaN,S
76,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S

In [842]:
# 'age', 'pclass'를 기준으로 정렬
t_df.sort_values(by=['Pclass', 'Age'], ascending=False)

# pclass는 오름차순으로 정렬, age는 내림차순으로 정렬

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
22,25,0,3,"Palsson, Miss. Torborg Danira",female,8.00,3,1,349909,21.0750,NaN,S
48,51,0,3,"Panula, Master. Juha Niilo",male,7.00,4,1,3101295,39.6875,NaN,S
61,64,0,3,"Skoog, Master. Harald",male,4.00,3,2,347088,27.9000,NaN,S
8,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S
14,17,0,3,"Rice, Master. Eugene",male,2.00,4,1,382652,29.1250,NaN,Q
5,8,0,3,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,21.0750,NaN,S
117,120,0,3,"Andersson, Miss. Ellis Anna Maria",female,2.00,4,2,347082,31.2750,NaN,S
56,59,1,2,"West, Miss. Constance Mirium",female,5.00,1,2,C.A. 34651,27.7500,NaN,S
41,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C
76,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S

In [843]:
# index를 기준으로 정렬
t_df = t_df.sort_index()
t_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,8,0,3,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,21.0750,NaN,S
8,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S
14,17,0,3,"Rice, Master. Eugene",male,2.00,4,1,382652,29.1250,NaN,Q
22,25,0,3,"Palsson, Miss. Torborg Danira",female,8.00,3,1,349909,21.0750,NaN,S
41,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C
48,51,0,3,"Panula, Master. Juha Niilo",male,7.00,4,1,3101295,39.6875,NaN,S
56,59,1,2,"West, Miss. Constance Mirium",female,5.00,1,2,C.A. 34651,27.7500,NaN,S
61,64,0,3,"Skoog, Master. Harald",male,4.00,3,2,347088,27.9000,NaN,S
76,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
117,120,0,3,"Andersson, Miss. Ellis Anna Maria",female,2.00,4,2,347082,31.2750,NaN,S

### 4-4. 데이터 접근/추출
* 범위 지정 : 직접 지정, 인덱서 이용
* 조건 지정

In [844]:
score_dict={'이름': ['정약용', '이순신', '이율곡', '홍길동'],
            '국어' : [70, 100, 90, 85],
            '영어' : [80, 80, 95, 100],
            '수학' : [100, 70, 90, 90]}
score_df = pd.DataFrame(score_dict)
score_df

    이름   국어   영어   수학
0  정약용   70   80  100
1  이순신  100   80   70
2  이율곡   90   95   90
3  홍길동   85  100   90

In [845]:
# 행 지정 -> 슬라이싱
score_df[2:3]

    이름  국어  영어  수학
2  이율곡  90  95  90

In [846]:
# 열 접근
score_df[['이름', '국어']]

    이름   국어
0  정약용   70
1  이순신  100
2  이율곡   90
3  홍길동   85

In [847]:
score_df.이름

0    정약용
1    이순신
2    이율곡
3    홍길동
Name: 이름, dtype: str

In [848]:
# 특정 (행,열)의 데이터 접근
score_df[:2][['이름', '국어']]

    이름   국어
0  정약용   70
1  이순신  100

In [849]:
score_df

    이름   국어   영어   수학
0  정약용   70   80  100
1  이순신  100   80   70
2  이율곡   90   95   90
3  홍길동   85  100   90

In [850]:
# 인덱서 이용 : 레이블(이름) 인덱서
# 행 접근
score_df.loc[1]

이름    이순신
국어    100
영어     80
수학     70
Name: 1, dtype: object

In [851]:
# 열 접근
score_df.loc[:,['이름', '국어']]

    이름   국어
0  정약용   70
1  이순신  100
2  이율곡   90
3  홍길동   85

In [852]:
# (행,열) 접근
score_df.loc[:1,'이름':'영어']

    이름   국어  영어
0  정약용   70  80
1  이순신  100  80

In [853]:
# 인덱서 이용 : 위치(숫자) 인덱서
# 행 접근
score_df.iloc[:1]

    이름  국어  영어   수학
0  정약용  70  80  100

In [854]:
# 열 접근
score_df.iloc[:,1:3]

    국어   영어
0   70   80
1  100   80
2   90   95
3   85  100

In [855]:
# (행,열) 접근
score_df.iloc[:2, 1:3]

    국어  영어
0   70  80
1  100  80

In [856]:
score_df

    이름   국어   영어   수학
0  정약용   70   80  100
1  이순신  100   80   70
2  이율곡   90   95   90
3  홍길동   85  100   90

In [857]:
# 조건 지정 추출 : Boolean Indexing
# 직접 지정 방식으로 행 추출
score_df[score_df.수학 >= 90]

    이름  국어   영어   수학
0  정약용  70   80  100
2  이율곡  90   95   90
3  홍길동  85  100   90

In [858]:
score_df[(score_df.국어 >= 90) & (score_df.수학 >= 90)]

    이름  국어  영어  수학
2  이율곡  90  95  90

In [859]:
score_df[score_df.이름.isin(['정약용', '이순신'])]

    이름   국어  영어   수학
0  정약용   70  80  100
1  이순신  100  80   70

In [860]:
# 인덱서 방식으로 행 추출
score_df.loc[score_df.수학 >= 90, ['이름', '수학']]

    이름   수학
0  정약용  100
2  이율곡   90
3  홍길동   90

In [861]:
# (행,열) 데이터 추출
score_df.loc[score_df.수학 >= 90, ['이름', '수학']]

    이름   수학
0  정약용  100
2  이율곡   90
3  홍길동   90

In [862]:
# 열 데이터에 조건 지정
score_df.loc[:,score_df.columns != '영어']

    이름   국어   수학
0  정약용   70  100
1  이순신  100   70
2  이율곡   90   90
3  홍길동   85   90

In [863]:
score_df.loc[:,score_df.dtypes == 'int']

    국어   영어   수학
0   70   80  100
1  100   80   70
2   90   95   90
3   85  100   90

In [ ]:
#[실습] 열기준으로 정렬하기

t_df.sort_values(by=['Age','Pclass'])
t_df.sort_values(by=['Age', 'Pclass'],ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
22,25,0,3,"Palsson, Miss. Torborg Danira",female,8.00,3,1,349909,21.0750,NaN,S
48,51,0,3,"Panula, Master. Juha Niilo",male,7.00,4,1,3101295,39.6875,NaN,S
56,59,1,2,"West, Miss. Constance Mirium",female,5.00,1,2,C.A. 34651,27.7500,NaN,S
61,64,0,3,"Skoog, Master. Harald",male,4.00,3,2,347088,27.9000,NaN,S
8,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S
41,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C
14,17,0,3,"Rice, Master. Eugene",male,2.00,4,1,382652,29.1250,NaN,Q
5,8,0,3,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,21.0750,NaN,S
117,120,0,3,"Andersson, Miss. Ellis Anna Maria",female,2.00,4,2,347082,31.2750,NaN,S
76,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S

In [ ]:
#[실습] 단순 인덱스로 범위를 지정해 데이터 가져오기

t_df[0:5]
t_df[0:1]
t_df[::3]
t_df[::-1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
22,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S
48,51,0,3,"Panula, Master. Juha Niilo",male,7.0,4,1,3101295,39.6875,NaN,S
56,59,1,2,"West, Miss. Constance Mirium",female,5.0,1,2,C.A. 34651,27.7500,NaN,S

In [ ]:
#[실습] 단순 인덱스로 범위 지정해 데이터 가져오기

t_df[:3]

In [ ]:
#[실습] 지정 범위의 열에서 데이터 가져오기
len(t_df.columns)

t_df[t_df.columns[0]]
t_df[t_df.columns[11]]
#t_df[t_df.columns[-1]]

22      25
48      51
56      59
61      64
8       11
41      44
14      17
5        8
117    120
76      79
Name: PassengerId, dtype: int64

In [ ]:
#[실습] 열이름으로 데이터 가져오기

age=t_df['Age']
print(type(age))

<class 'pandas.Series'>

In [ ]:
t_df['Age']
t_df.Age

22     8.00
48     7.00
56     5.00
61     4.00
8      4.00
41     3.00
14     2.00
5      2.00
117    2.00
76     0.83
Name: Age, dtype: float64

In [868]:
#[실습] 열 이름과 위치를 이용해 데이터 가져오기

print(t_df[t_df.columns[0]][0])
print(t_df['Age'][0])
print(t_df[t_df.columns[0]][2])
print(t_df[t_df.columns[-1]][0])
type(t_df[t_df.columns[0]][0])

8
2.0
17
S

numpy.int64

In [ ]:
print(t_df[t_df.columns[0]][2:6])
print(t_df[t_df.columns[0]][:-1])
print(t_df[t_df.columns[0]][::3])
print(t_df[t_df.columns[0]][-1:])
print(t_df[t_df.columns[0]][::-1])

14    17
22    25
41    44
48    51
Name: PassengerId, dtype: int64
5      8
8     11
14    17
22    25
41    44
48    51
56    59
61    64
76    79
Name: PassengerId, dtype: int64
5        8
22      25
56      59
117    120
Name: PassengerId, dtype: int64
117    120
Name: PassengerId, dtype: int64
117    120
76      79
61      64
56      59
48      51
41      44
22      25
14      17
8       11
5        8
Name: PassengerId, dtype: int64

In [ ]:
t_df[['Pclass', 'Name', 'Sex']]
t_df[[t_df.columns[2], t_df.columns[3], t_df.columns[4]]]

     Pclass                                      Name     Sex
5         3            Palsson, Master. Gosta Leonard    male
8         3           Sandstrom, Miss. Marguerite Rut  female
14        3                      Rice, Master. Eugene    male
22        3             Palsson, Miss. Torborg Danira  female
41        2  Laroche, Miss. Simonne Marie Anne Andree  female
48        3                Panula, Master. Juha Niilo    male
56        2              West, Miss. Constance Mirium  female
61        3                     Skoog, Master. Harald    male
76        2             Caldwell, Master. Alden Gates    male
117       3         Andersson, Miss. Ellis Anna Maria  female

In [ ]:
t_df[[t_df.columns[2], t_df.columns[3], t_df.columns[4]]][2:15:3]

    Pclass                           Name   Sex
14       3           Rice, Master. Eugene  male
48       3     Panula, Master. Juha Niilo  male
76       2  Caldwell, Master. Alden Gates  male

In [ ]:
t_df = t_df.reset_index(drop=True)

print(t_df[t_df.columns[0]][0])
print(t_df[t_df.columns[0]][2])
# print(t_df[t_df.columns[0]][-1])
print(type(t_df[t_df.columns[0]][0]))

8
17
<class 'numpy.int64'>

In [866]:
t_df.loc[0]

PassengerId                                 8
Survived                                    0
Pclass                                      3
Name           Palsson, Master. Gosta Leonard
Sex                                      male
Age                                       2.0
SibSp                                       3
Parch                                       1
Ticket                                 349909
Fare                                   21.075
Cabin                                     NaN
Embarked                                    S
Name: 0, dtype: object

In [ ]:
t_df.loc[0:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.075,NaN,S

In [ ]:
t_df.loc[0:10:2]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.075,NaN,S

In [ ]:
t_df.loc[:, 'Age']

5      2.00
8      4.00
14     2.00
22     8.00
41     3.00
48     7.00
56     5.00
61     4.00
76     0.83
117    2.00
Name: Age, dtype: float64

In [ ]:
t_df.loc[:,['Age', 'Sex']]

      Age     Sex
5    2.00    male
8    4.00  female
14   2.00    male
22   8.00  female
41   3.00  female
48   7.00    male
56   5.00  female
61   4.00    male
76   0.83    male
117  2.00  female

In [ ]:
t_df.loc[3:7, ['Age', 'Sex']]

   Age   Sex
5  2.0  male

In [ ]:
t_df.loc[2:5, 'Survived': 'Age']

   Survived  Pclass                            Name   Sex  Age
5         0       3  Palsson, Master. Gosta Leonard  male  2.0

In [ ]:
t_df.iloc[0]

PassengerId                                 8
Survived                                    0
Pclass                                      3
Name           Palsson, Master. Gosta Leonard
Sex                                      male
Age                                       2.0
SibSp                                       3
Parch                                       1
Ticket                                 349909
Fare                                   21.075
Cabin                                     NaN
Embarked                                    S
Name: 5, dtype: object

In [ ]:
t_df.iloc[0:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
14,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
22,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S
41,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.0,1,2,SC/Paris 2123,41.5792,NaN,C

In [ ]:
t_df.iloc[0:10:3]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.075,NaN,S
22,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.075,NaN,S
56,59,1,2,"West, Miss. Constance Mirium",female,5.0,1,2,C.A. 34651,27.750,NaN,S
117,120,0,3,"Andersson, Miss. Ellis Anna Maria",female,2.0,4,2,347082,31.275,NaN,S

In [ ]:
t_df.iloc[:, [0, 2]]

     PassengerId  Pclass
5              8       3
8             11       3
14            17       3
22            25       3
41            44       2
48            51       3
56            59       2
61            64       3
76            79       2
117          120       3

In [ ]:
t_df.iloc[1:5, [0, 2]]

    PassengerId  Pclass
8            11       3
14           17       3
22           25       3
41           44       2

## 4-5. 그룹별로 요약하여 데이터 확인
* value_counts()
* groupby()
* pivot_table()

In [ ]:
sample_file = 'data/sales_sample.csv'

In [ ]:
# 샘플 파일 로딩

In [ ]:
# 지역별 판매 기록의 개수

In [ ]:
# 상품별 판매 기록의 개수와 비율

In [ ]:
# 지역과 상품의 조합별 판매 기록 개수

In [ ]:
# 지역별 총매출

In [ ]:
# 상품별 평균 매출

In [ ]:
# 지역별 판매수량의 합계와 매출의 합계

In [ ]:
# 지역과 상품별 평균 매출

In [ ]:
# 지역별·상품별 총매출을 구하고 행과 열의 합계 표시